### ISSUE TITLE
Ruby off Rails scholarship

### ISSUE THREAD

**Issue by judionrails** [jwo/feedback#1]
Hi Jesse! 
I just found out about your course & I'd like to know when your next one will be.  I am super excited to learn about the scholarship for women that you offer & I'm interested in applying for it for the next course.

I look forward to hearing from you.

Thank you, 
Judi Lynn Ott  aka jlo  :-)
judionrails@yahoo.com
713.269.5834

**Comment by jwo** [comment]
Hi jlo!

That's really awesome! I'm planning on having a course every season -- so 6 weeks for the course, then 6 week break. That currently looks like October 30th or so would start the next Fall course.

I'll definitely be doing the scholarship again -- very cool about you wanting to apply then!
- jesse

**Comment by judionrails** [comment]
Great, thank you Jesse!  I'll touch base with you in October to confirm the start date.  

~ jlo
