### ISSUE TITLE
JSON / Devise .... 

### ISSUE THREAD

**Issue by rocklobby** [jwo/feedback#2]
Love your solution ... works great on localhost ... but Heroku fails to start up.   Complains about 

uninitialized constant Devise::Controllers::DeviseController (NameError)

Note:  I just posted same question on your web page.   Thank you in advance both for the solution and any assistance you can supply.

**Comment by jwo** [comment]
@rocklobby hi! Doesn't appear to be related to Heroku at all. I think it's possible your Gemfile isn't committed to git, so Heroku is loading an old Gemfile that doesn't reference devise.

**Comment by rocklobby** [comment]
SOLVED.   

After plenty of hack / sending to Heroku / crashes .... what worked was to simply use:

```
  "Devise" instead of "Devise::Controllers::DeviseController"
```

This is using latest gems as of today:  9/9/2012 ... ( I didn't specify versions ).    On Ruby 1.9.3  ( Heroku has 1.9.1 ) and latest RAILS  ( 3.2... )

THANK YOU FOR THE POSTING.

I did ignore the base class .... since I didn't know why you had it.  And thus derived both controllers from Devise.  And got rid of  "Internal" in "InternalHelpers" as the latter is no longer part of Devise.

**Comment by jwo** [comment]
Cool. If you'll create a gist or posting, I'll link to the updated code.

Also: to speed up your feedback cycle later, you can just go to production mode locally (vs deploying to heroku).

**Comment by tknazn** [comment]
I have the same question as well. Can you explain about the base controller?
