### ISSUE TITLE
Store auth_token into user's Iphone

### ISSUE THREAD

**Issue by stefanocdn** [jwo/feedback#3]
Hi Jesse,

thanks for your article https://gist.github.com/jwo/1255275. I'm currently working on a mobile app with rails back-end.

I was wondering, once the user gets the auth_token back, how would you store it safely for later authentified calls?

Thanks for your help,

Stephane

**Comment by jwo** [comment]
I'm asking a friend for advice, will reply later today.

**Comment by subdigital** [comment]
You can securely store things like this on the Keychain on iOS.  While keychain isn't the most friendly of APIs, there are some good wrappers that make it as easy to use as a persistent dictionary.  I usually lean on [SSKeychain](https://github.com/soffes/sskeychain).
